name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Libs
      run: sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.0-37
    - name: Build
      run: cargo build --verbose
